<?php 
include('includes/db.php');
include('includes/header.php'); 
?>

<h1>Consultation Publique</h1>
<p>Visualisation de la dernière mesure enregistrée pour chaque salle équipée[cite: 3].</p>

<table>
    <thead>
        <tr>
            <th>Bâtiment</th>
            <th>Salle</th>
            <th>Capteur (Type)</th>
            <th>Valeur Actuelle</th>
            <th>Date & Horaire</th>
        </tr>
    </thead>
    <tbody>
        <?php
        // Fetch last measurement generated by each sensor from the custom MySQL view or subquery
        $query = "SELECT b.nom AS b_nom, s.nom AS s_nom, c.type AS c_type, c.unite, m.valeur, m.date, m.horaire 
                  FROM mesure m 
                  JOIN capteur c ON m.id_capteur = c.id 
                  JOIN salle s ON c.id_salle = s.id 
                  JOIN batiment b ON s.id_batiment = b.id 
                  WHERE m.id IN (SELECT MAX(id) FROM mesure GROUP BY id_capteur)";
        
        $result = mysqli_query($conn, $query); //
        
        if ($result && mysqli_num_rows($result) > 0) {
            while ($row = mysqli_fetch_assoc($result)) {
                echo "<tr>";
                echo "<td>" . htmlspecialchars($row['b_nom']) . "</td>";
                echo "<td>" . htmlspecialchars($row['s_nom']) . "</td>";
                echo "<td>" . htmlspecialchars($row['c_type']) . "</td>";
                echo "<td>" . htmlspecialchars($row['valeur']) . " " . htmlspecialchars($row['unite']) . "</td>";
                echo "<td>" . htmlspecialchars($row['date']) . " " . htmlspecialchars($row['horaire']) . "</td>";
                echo "</tr>";
            }
        } else {
            echo "<tr><td colspan='5'>No measurements available in the system database[cite: 4].</td></tr>";
        }
        ?>
    </tbody>
</table>

<?php include('includes/footer.php'); ?>
